-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgBM+XwwyBwAsP3EnP
7tHN+FE29FmYQwZBkRgHkzg5zM+gCgYIKoZIzj0DAQehRANCAAQ4ihCB/SuycRKx
MscneGbFJNyR65gPQrL58gN1FMDmesXX2l6xEhddG2/mmGWnAn3cIFnnlbjnc0v8
JgMVpVcu
-----END PRIVATE KEY-----