-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgYjZnSIjZpS4gJmi4
1Qrf9LdkHzIJatQY+AEJwpk43+CgCgYIKoZIzj0DAQehRANCAAR7rEqWZdjEgHQX
IYdjd5eDLW/TuQi/KuLMXNG7HNk1YkdxaqimtDLnWZJeukYGwYnGhxjbcEb1U6ih
stw+Yjta
-----END PRIVATE KEY-----